part:
    description: Create or edit a part routing.
    aliases: ['p']
    options:
        [
            '--macro', '-M', # Runs the new part macro
            '--update', '-U', # Runs the update existing part macro
            '--locator', '-L' # Runs only the locator macro
        ]
    args:
        - l # laser
        - e # edgegrind
        - b # small brake
        - B # large brake
        - P # paint part
        - s # saw cut
        - d # drill and tap
        - w # weld at MED BENT
    func: part # commands.part
    data:
        l: 
            record: ['250001', 'MACHINIST', 'LASER CUT PART']
            params: 
                thickness:
                    - 'Enter material thickness: '
                    - '^\d*\.\d*$|^\d*$'
                grade: 
                    - 'Enter material grade: '
                    - '^EMS \d*-\d*$|^ems \d*-\d*$'
                perimeter: 
                    - 'Enter part perimeter: '
                    - '^\d*\.\d*$|^\d*$'
            calc_func: laser
        e: 
            record: ['EDGEGRIND', 'MACH OPER', 'GRIND EDGES']
            params:
                short: 
                    - 'Enter part shortest side: '
                    - '^\d*\.\d*$|^\d*$'
                long: 
                    - 'Enter part longest side: '
                    - '^\d*\.\d*$|^\d*$'
            calc_func: edgegrind
        d:
            record: ['109001', 'MACHINIST', 'DRILL TO PRINT']
            params:
                size: 
                    - 'Enter drill bit size: '
                    - '^\d/\d$|^1$|^1 \d/\d$'
                num:
                    - 'Enter number of holes: '
                    - '^\d*$'
            calc_func: drill
        b:
            record: ['101001', 'MACHINIST', 'FORM BENDS']
            params:
                bends: 
                    - 'Enter number of bends: '
                    - '^[1-9]$|^1[0-2]$'
                weight: 
                    - 'Enter weight of part being bent: '
                    - '^\d*\.\d*$|^\d*$'
            calc_func: bend
        B: 
            record: ['LRG BRAKE', 'MACH OPER', 'FORM BENDS']
            params:
                bends: 
                    - 'Enter number of bends: '
                    - '^[1-9]$|^1[0-2]$'
                weight: 
                    - 'Enter weight of part being bent: '
                    - '^\d*\.\d*$|^\d*$'
            calc_func: bend
        P: 
            record: ['095424', 'PAINTER', 'POWDER PAINT PART']
            params:
                length: 
                    - 'Enter paint hang length: '
                    - '^\d*\.\d*$|^\d*$'
            calc_func: paint
        s: 
            record: ['104001', 'MACH OPER', 'CUT TO LENGTH']
            params:
                dist: 
                    - 'Enter distance to cut: '
                    - '^\d*\.\d*$|^\d*$'
                steel:
                    - 'Is this a steel part? (y/n): '
                    - '^Y$|^N$|^y$|^n$'
            calc_func: saw

weldment:
    description: Create or edit a weldment routing.
    aliases: ['w', 'weld']
    options:
        [
            '--macro', '-M', # Runs the new part macro
            '--update', '-U', # Runs the update existing part macro
            '--locator', '-L' # Runs only the locator macro
        ]
    args:
        - mb # medium bent
        - mp # medium parts
        - sub # subbases
        - P # paint weldment
    func: weldment # commands.weldment
    data:
        mb: ['MED BENT', 'WELDER', 'WELD PART']
        mp: ['400001', 'WELDER', 'WELD PART']
        sub: ['465001', 'WELDER', 'WELD PART']
        P: ['095424', 'PAINTER', 'POWDER PAINT PART']

exit:
    description: Exit the program
    aliases: ['quit', 'q', 'stop']
    options: []
    args: []
    func: exit # commands.exit

tutorial:
    description: Walk through the tutorial
    aliases: []
    options: []
    args: []
    func: tutorial # commands.tutorial

clear:
    description: Clear the screen
    aliases: []
    options: []
    args: []
    func: clear # commands.clear