part:
    description: Create a new part routing.
    help: |
        [yellow]l[/yellow]            Lasers
        [yellow]e[/yellow]            Edgegrind
        [yellow]b[/yellow]            Small Brake
        [yellow]B[/yellow]            Large Brake
        [yellow]P[/yellow]            Paint part
        [yellow]s[/yellow]            Saw cut
        [yellow]d[/yellow]            Drill and Tap

        i.e. [yellow]>> part l e B P[/yellow]
                Starts the wizard for a large bent painted piece part

        [cyan]-m, --macro[/cyan]    Runs the new part macro
        [cyan]-l, --locator[/cyan]  Runs only the locator macro
    
        i.e. [yellow]>> part [/yellow][cyan]-m[/cyan][yellow] l e B P[/yellow]
    aliases: ['p']
    options:
        [
            '--macro', '-m', # Runs the new part macro
            '--locator', '-l' # Runs only the locator macro
        ]
    args:
        - l # laser
        - e # edgegrind
        - b # small brake
        - B # large brake
        - P # paint part
        - s # saw cut
        - d # drill and tap
        - w # weld at MED BENT
    func: part # commands.part
    data:
        l: 
            record: ['250001', 'MACHINIST', 'LASER CUT PART']
            params: 
                thickness:
                    - 'Enter material thickness: '
                    - '^\d*\.\d*$|^\d*$'
                grade: 
                    - 'Enter material grade: '
                    - '^EMS \d*-\d*$|^ems \d*-\d*$'
                perimeter: 
                    - 'Enter part perimeter: '
                    - '^\d*\.\d*$|^\d*$'
            calc_func: laser
        e: 
            record: ['EDGEGRIND', 'MACH OPER', 'GRIND EDGES']
            params:
                short: 
                    - 'Enter part shortest side: '
                    - '^\d*\.\d*$|^\d*$'
                long: 
                    - 'Enter part longest side: '
                    - '^\d*\.\d*$|^\d*$'
            calc_func: edgegrind
        d:
            record: ['109001', 'MACHINIST', 'DRILL TO PRINT']
            params:
                size: 
                    - 'Enter drill bit size: '
                    - '^\d/\d$|^1$|^1 \d/\d$'
                num:
                    - 'Enter number of holes: '
                    - '^\d*$'
            calc_func: drill
        b:
            record: ['101001', 'MACHINIST', 'FORM BENDS']
            params:
                bends: 
                    - 'Enter number of bends: '
                    - '^[1-9]$|^1[0-2]$'
                weight: 
                    - 'Enter weight of part being bent: '
                    - '^\d*\.\d*$|^\d*$'
            calc_func: bend
        B: 
            record: ['LRG BRAKE', 'MACH OPER', 'FORM BENDS']
            params:
                bends: 
                    - 'Enter number of bends: '
                    - '^[1-9]$|^1[0-2]$'
                weight: 
                    - 'Enter weight of part being bent: '
                    - '^\d*\.\d*$|^\d*$'
            calc_func: bend
        P: 
            record: ['095424', 'PAINTER', 'POWDER PAINT PART']
            params:
                length: 
                    - 'Enter paint hang length: '
                    - '^\d*\.\d*$|^\d*$'
            calc_func: paint
        s: 
            record: ['104001', 'MACH OPER', 'CUT TO LENGTH']
            params:
                dist: 
                    - 'Enter distance to cut: '
                    - '^\d*\.\d*$|^\d*$'
                steel:
                    - 'Is this a steel part? (y/n): '
                    - '^Y$|^N$|^y$|^n$'
            calc_func: saw
        w: 
            record: ['400001', 'WELDER', 'WELD PART']
            params:
                size: 
                    - 'Enter weld size: '
                    - '^\d*\.\d*$'
                weight: 
                    - 'Enter weight of part being welded: '
                    - '^\d*\.\d*$|^\d*$'
                inches: 
                    - 'Enter total length to weld: '
                    - '^\d*\.\d*$|^\d*$'
            calc_func: weldpart

weld:
    description: Create a new weldment routing.
    help: |
        [yellow]mp[/yellow]           Medium Parts
        [yellow]mb[/yellow]           Medium Bent
        [yellow]sub[/yellow]          Subbases
        [yellow]P[/yellow]            Paint line

        i.e. [yellow]>> weld mp P[/yellow]
                Starts the wizard for a painted weldment

        [cyan]-m, --macro[/cyan]    Runs the new part macro
        [cyan]-l, --locator[/cyan]  Runs only the locator macro
    
        i.e. [yellow]>> weld [/yellow][cyan]-m[/cyan][yellow] mp P[/yellow]
    aliases: ['w', 'weldment']
    options:
        [
            '--macro', '-m', # Runs the new part macro
            '--locator', '-l' # Runs only the locator macro
        ]
    args:
        - mb # medium bent
        - mp # medium parts
        - sub # subbases
        - mf # medium forestry
        - P # paint weldment
    func: weldment # commands.weldment
    data:
        mb: 
            record: ['MED BENT', 'WELDER', 'WELD PART']
            params:
                size: 
                    - 'Enter weld size: '
                    - '^\d*\.\d*$'
                weight: 
                    - 'Enter weight of part being welded: '
                    - '^\d*\.\d*$|^\d*$'
                num_parts: 
                    - 'Enter number of parts to weld: '
                    - '^[1-9]$|^[1-3][0-9]$'
                inches: 
                    - 'Enter total length to weld: '
                    - '^\d*\.\d*$|^\d*$'
                fixturing: 
                    - 'Part has fixturing? (y/n): '
                    - '^Y$|^N$|^y$|^n$'
            calc_func: weld
        mp: 
            record: ['400001', 'WELDER', 'WELD PART']
            params:
                size: 
                    - 'Enter weld size: '
                    - '^\d*\.\d*$'
                weight: 
                    - 'Enter weight of part being welded: '
                    - '^\d*\.\d*$|^\d*$'
                num_parts: 
                    - 'Enter number of parts to weld: '
                    - '^[1-9]$|^[1-3][0-9]$'
                inches: 
                    - 'Enter total length to weld: '
                    - '^\d*\.\d*$|^\d*$'
                fixturing: 
                    - 'Part has fixturing? (y/n): '
                    - '^Y$|^N$|^y$|^n$'
            calc_func: weld
        sub: 
            record: ['465001', 'WELDER', 'WELD PART']
            params:
                size: 
                    - 'Enter weld size: '
                    - '^\d*\.\d*$'
                weight: 
                    - 'Enter weight of part being welded: '
                    - '^\d*\.\d*$|^\d*$'
                num_parts: 
                    - 'Enter number of parts to weld: '
                    - '^[1-9]$|^[1-3][0-9]$'
                inches: 
                    - 'Enter total length to weld: '
                    - '^\d*\.\d*$|^\d*$'
                fixturing: 
                    - 'Part has fixturing? (y/n): '
                    - '^Y$|^N$|^y$|^n$'
            calc_func: weld
        
        mf: 
            record: ['FORESTRY', 'WELDER', 'WELD PART']
            params:
                size: 
                    - 'Enter weld size: '
                    - '^\d*\.\d*$'
                weight: 
                    - 'Enter weight of part being welded: '
                    - '^\d*\.\d*$|^\d*$'
                num_parts: 
                    - 'Enter number of parts to weld: '
                    - '^[1-9]$|^[1-3][0-9]$'
                inches: 
                    - 'Enter total length to weld: '
                    - '^\d*\.\d*$|^\d*$'
                fixturing: 
                    - 'Part has fixturing? (y/n): '
                    - '^Y$|^N$|^y$|^n$'
            calc_func: weld
        P: 
            record: ['095424', 'PAINTER', 'POWDER PAINT WELDMENT']
            params:
               record: ['095424', 'PAINTER', 'POWDER PAINT PART']
            params:
                length: 
                    - 'Enter paint hang length: '
                    - '^\d*\.\d*$|^\d*$'
            calc_func: paint

exit:
    description: Exit the program
    help: |
        Gracefully exits the program

        i.e. [yellow]>> exit[/yellow]

    aliases: ['quit', 'q', 'stop']
    options: []
    args: []
    func: exit # commands.exit

tutorial:
    description: Walk through the tutorial
    help: |
        i.e. [yellow]>> tutorial[/yellow]

        If you have questions during the tutorial, talk to a 24A mfg engineer!

    aliases: []
    options: []
    args: []
    func: tutorial # commands.tutorial

clear:
    description: Clear the screen
    help: |
        Clears the screen. Equivalent to [yellow]cls[/yellow] on Windows and [yellow]clear[/yellow] on Linux.

        i.e. [yellow]>> clear[/yellow]
    aliases: []
    options: []
    args: []
    func: clear # commands.clear