[laser]
# 4k CO2 configuration table
# [thickness, speed, cuttable grade(s)]
4k_CO2 = [  [0.105, 177, ['EMS 1-1']],
            [0.135,	150, ['EMS 2-1']],
            [0.179, 126, ['EMS 2-14']],
            [0.188, 126, ['EMS 2-1']],
            [0.25, 102, ['EMS 2-1', 'EMS 2-14']],
            [0.313, 87, ['EMS 2-1', 'EMS 2-14']],
            [0.375, 63, ['EMS 2-1', 'EMS 2-14']],
            [0.5, 57, ['EMS 2-1', 'EMS 2-6', 'EMS 2-14']],
            [0.75, 31, ['EMS 2-5']],
            [1, 27, ['EMS 2-1']],
            [1.25, 26, ['EMS 2-1']],
            [1.5, 25, ['EMS 2-6']]
            ]

# 6k CO2 configuration table
# [thickness, speed, cuttable grade(s)]
6k_CO2 = [  [0.105, 245, ['EMS 1-1']],
            [0.135,	208, ['EMS 2-1']],
            [0.179, 174, ['EMS 2-14']],
            [0.188, 174, ['EMS 2-1']],
            [0.25, 140, ['EMS 2-1', 'EMS 2-14']],
            [0.313, 120, ['EMS 2-1', 'EMS 2-14']],
            [0.375, 86, ['EMS 2-1', 'EMS 2-14']],
            [0.5, 79, ['EMS 2-1', 'EMS 2-6', 'EMS 2-14']],
            [1, 37, ['EMS 2-1']],
            [1.25, 36, ['EMS 2-1']],
            [1.5, 35, ['EMS 2-6']]
            ]

# 6k Fiber configuration table
# [thickness, speed, cuttable grade(s)]
6k_Fiber = [[0.105, 650, ['EMS 1-1']],
            [0.135,	492, ['EMS 2-1']],
            [0.188, 270, ['EMS 2-1']],
            [0.25, 225, ['EMS 2-1']],
            [0.313, 120, ['EMS 2-1']],
            [0.375, 81, ['EMS 2-1']],
            [0.5, 55, ['EMS 2-1']]
            ]

# 12k Fiber configuration table
# [thickness, speed, cuttable grade(s)]
12k_Fiber = [[0.105, 1280, ['EMS 1-1']],
            [0.135,	1000, ['EMS 2-1']],
            [0.188, 602, ['EMS 2-1']],
            [0.25, 461, ['EMS 2-1']],
            [0.313, 276, ['EMS 2-1']],
            [0.375, 83, ['EMS 2-1']],
            [0.5, 55, ['EMS 2-1']]
            ]

[drill]
# Bit size | routed time
"1/8" = 0.9
"1/4" = 1
"3/8" = 1.1
"1/2" = 1.2
"5/8" = 1.3
"3/4" = 1.4
"7/8" = 1.5
"1" = 1.6
"1 1/8" = 1.7
"1 1/4" = 1.8
"1 3/8" = 1.9
"1 1/2" = 2
"1 5/8" = 2.1
"1 3/4" = 2.2
"1 7/8" = 2.3

[saw]
# Shortest cuttable length | routed time
1 = 0.33
2 = 0.5
3 = 0.67
4 = 0.83
5 = 1
6 = 1.17
7 = 1.33
8 = 1.5
9 = 1.67
10 = 1.83
11 = 2
12 = 2.17
13 = 2.33
14 = 2.5
15 = 2.67
16 = 2.83
17 = 3
18 = 3.17
19 = 3.33
20 = 3.5

[bend]
[bend.small]
# Number of bends | routed time
1 = 1.5
2 = 2.2
3 = 2.9
4 = 3.6
5 = 4.3
6 = 5
7 = 5.7
8 = 6.4
9 = 7.1
10 = 7.8
11 = 8.5
12 = 9.2

[bend.large]
# Number of bends | routed time
1 = 4
2 = 5
3 = 6
4 = 7
5 = 8
6 = 9
7 = 10
8 = 11
9 = 12
10 = 13
11 = 14
12 = 15

[weld]
# Size | weld speed
size = [[0.13, 16],
        [0.18, 15],
        [0.19, 15],
        [0.25, 13], 
        [0.31, 10],
        [0.38, 7]]

# Part prep factor
part_prep = 2

# Part fit-up factor
part_fitup = [0, 0.95, 1]

# Breaks factor
breaks_factor = 1.04166666666667