intro: |
 [cyan]______________________________________________________________________________[/cyan][bold white]
       ______  _____  _     _ _______ _____ __   _  ______ _______          
      |_____/ |     | |     |    |      |   | \  | |  ____ |______          
      |    \_ |_____| |_____|    |    __|__ |  \_| |_____| ______|          
                                                                            
 _______ _______ _______  ______  _____       _______  _____   _____        
 |  |  | |_____| |       |_____/ |     |         |    |     | |     | |     
 |  |  | |     | |_____  |    \_ |_____|         |    |_____| |_____| |____
 
 [/bold white][cyan]______________________________________________________________________________[/cyan]


part:
  macro_option: '[bold cyan]--macro[/bold cyan] option selected.'
  update_option: '[bold cyan]--update[/bold cyan] option selected.'
  locator_option: '[bold cyan]--locator[/bold cyan] option selected.'
  error:
    not_implemented: '[bold red]Not implemented yet.[/bold red]'

route:
  routings_item_box: '[bold cyan]Ctrl[/bold cyan] + [bold cyan]Shift[/bold cyan] + [bold cyan]Right Arrow[/bold cyan] in the Oracle routings item box...'
  routing_complete: '[bold green]Routing completed successfully.[/bold green]'
  zoom_item_box: '[bold cyan]Ctrl[/bold cyan] + [bold cyan]Shift[/bold cyan] + [bold cyan]Right Arrow[/bold cyan] in the Zoom -> Item Number box...'
  zoom_item_complete: '[bold green]Zoom -> Item Number complete.[/bold green]'
  locator_box: '[bold cyan]Ctrl[/bold cyan] + [bold cyan]Shift[/bold cyan] + [bold cyan]Right Arrow[/bold cyan] in the POU locator box...'
  locator_complete: '[bold green]Locator complete.[/bold green]'


tutorial:
  welcome: |
    [bold green]Welcome to the tutorial.[/bold green]
    This is intended to be a step-by-step, guided tutorial for the routings macro tool.
    It will walk you through the process of creating a part routing.
    You should already be familiar with:
    - The basic Oracle applications, including Routings and Item Master
    - How to open a print with PDF Dive or Part Information
    - Fab shop basics, and what it takes to physically make a part.
    [bold green]Good luck![/bold green]
    [yellow]Press ctrl + c to exit at any time.[/yellow]

    Continue? (y/n): 

  step_1: |
    [bold green]Step 1: Open a print.[/bold green]
    Highlight this part number and press [yellow]Ctrl[/yellow] + [yellow]~[/yellow] to open with PDF dive.
        991850322
    Alternatively, you can open a print with Part Information.

    [bold green]Did the print open successfully? (y/n)[/bold green]

  step_2: |
    [bold green]Step 2: Create a new part routing.[/bold green]
    This is a single piece part, a perfect use case for this tool.

    This part will be routed to the [cyan]lasers[/cyan], then through [cyan]edge grind[/cyan], then the [cyan]small brake[/cyan], and finally the [cyan]paint line[/cyan].
    Enter the following command:
      [yellow]>> part l e b P[/yellow]
    
  step_3: |
    Note that to run the macro, you need to inlude the --macro or -M option. We won't do that in this tutorial.

    [bold green]Step 3: Follow the wizard.[/bold green]
  
  step_4: |
    [bold green]Step 4: Check the results.[/bold green]
    These are the values you should have entered:
        Enter material thickness: [yellow]0.105[/yellow]
        Enter material grade: [yellow]EMS 1-1[/yellow]
        Enter part perimeter: [yellow]38.09[/yellow]
        Enter part shortest side: [yellow]3.5[/yellow]
        Enter part longest side: [yellow]10.516[/yellow]
        Enter number of bends: [yellow]1[/yellow]
        Enter weight of part being bent: [yellow]0.8[/yellow]
        Enter minimum paintable length: [yellow]3.5[/yellow]
        
  step_5: |
    If you are having issues understanding where numbers went awry, run the [yellow]>> part[/yellow] command again or check with your supervisor.

    Good luck using this tool. Email or teams david.alexander@altec.com with questions or suggestions.
  
  error: |
      [bold red]Encountered an error while running the tutorial.[/bold red]
      Some common reasons for this are:
      - You entered values that couldn't be calculated
      - You pressed ctrl + c while entering numbers into the calculator

      Run [yellow]>> tutorial[/yellow] to try again or run a different command.
      

